---
- name: CONFIGURE OSPF
  hosts: CSR1kv
  gather_facts: false
  connection: local
  tasks:
  - name: SET OSPF CONFIGURATION
    ios_config:
      parents: "router ospf 1"
      lines:
      - network 10.20.20.0 0.0.0.255 area 0
  - name: SHOW IPv4 INTERFACE BRIEF
    ios_command:
     commands:
     - show ip ospf 1
    register: output
  - name: SAVE OUTPUT ./ios_configurations/
    copy:
      content: "{{ output.stdout[0] }}"
      dest: "ios_configurations/OSPF_Single_Area{{ inventory_hostname }}.txt"