---
- name: CONFIGURE IPv4 ADDRESSING
  hosts: CSR1kv
  gather_facts: false
  connection: local
  tasks:
  - name: SET IPv4 ADDRESS
    ios_config:
      parents: "interface Loopback0"
      lines:
      - description IPv4 ADDRESS
      - ip address 10.20.20.10 255.255.255.0
  - name: SHOW IPv4 INTERFACE BRIEF
    ios_command:
     commands:
     - show ip interface brief
    register: output
  - name: SAVE OUTPUT ./ios_configurations/
    copy:
      content: "{{ output.stdout[0] }}"
      dest: "ios_configurations/IPv4_output_{{ inventory_hostname }}.txt"